name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  checkPullRequest:
    name: Check pull-request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install && npm install http-server
      - name: Run build
        run: npm run build
      - name: Run application for functional tests
        run: npx http-server dist/spa &
      - name: Run functional tests
        run: npm run test:e2e
